# Dependencies
markdown: kramdown
highlighter: pygments
url: www.unswcsa.com

# Permalinks
permalink: pretty
relative_permalinks: true

# Title
title: UNSWCSA

paginate: 5
paginate_path: "/blog/page:num/"
